image_topic: "/camera/rgb/image_rect_color"
cam_info_topic: "/camera/rgb/camera_info"
useDepth: true #if true specify a valid depth topic
depth_topic: "/camera/depth_registered/sw_registered/image_rect"
benchmark_3D: false  #will compute 3D Keypoint Error / needs depth
output_path: "/tmp"